version: "3.1"
services:
 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    ports:
      - "9090:9090"
    networks:
      - "monitoring"
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    #   - path/to-your/grafana.ini:/etc/grafana/grafana.ini
      - ./config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    # links:
    networks:
      - "monitoring"

networks:
  monitoring:
    name: "monitoring"
